### PR TITLE
Fix CLI and use old headless by default in chromium based browsers

### LINKED ISSUE #155: The screenshot of page is not full page
Hi,

I got a problem when I render image using Html2Image. The screenshot of page is not full page. It has blank in end page.  Please help me solve this problem. Thanks!

blank_not_fullpage

### LINKED ISSUE #156: [Bug] Unable to Use Command hti -U
```
D:\Windows\Download>hti -U https://www.google.com.hk/
Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-465SP1L\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator.DESKTOP-465SP1L\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator.DESKTOP-465SP1L\AppData\Local\Programs\Python\Python310\Scripts\hti.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator.DESKTOP-465SP1L\AppData\Local\Programs\Python\Python310\lib\site-packages\html2image\cli.py", line 66, in main
    paths = hti.screenshot(
TypeError: Html2Image.screenshot() got an unexpected keyword argument 'browser_executable'
```

### PR DESCRIPTION
**Pull request by satheler**
fix #156
fix #155

Reference links
- https://developer.chrome.com/docs/chromium/new-headless
- https://developer.chrome.com/blog/chrome-headless-shell

> Note: Passing the --headless command-line flag without an explicit value still activates the old Headless mode, but we intend to change this default. We intend to remove the old Headless from the Chrome binary and stop supporting this mode in Puppeteer in 2024. Simultaneously, we'll make old Headless mode available as a standalone binary for users who can't upgrade yet.

The moment mentioned in the quote above has arrived.

### CODE REVIEW

**Comment by satheler** [comment]
@vgalin review please

**Review by vgalin — COMMENTED** [review]
In the future, you could consider keeping the comma at the end of the line, it makes diffs cleaner for current and future commits on this line.

**Review by vgalin — CHANGES_REQUESTED** [review]
Could you use a shorter name for the `should_use_new_headless_mode` attribute ? Maybe `use_new_headless_mode`, or even `use_new_headless`.

**Comment by vgalin** [comment]
Thank you for taking the time to create this PR. Along with the (minor) reviews, I have a question myself: 

What happens if a user is using an older version of Chrome(ium)? Does it break the headless mode because `headless=new|old` is used instead of just `headless`, or does it still work fine?

Regardless of the outcome, I see two possible courses of action:
- Do nothing: If someone is using an older Chrome version, they’ll need to use an older version of html2image as well.
- Allow the user to choose between `headless=new`, `headless=old`, and `headless`. Currently, the attribute you added sets headless to `headless=new` or `headless=old` based on its truthiness. Perhaps a third option could be introduced: if the attribute is `None`, then the value is simply `headless` without any suffix.

Do as you see fit, I don't have a preference at the moment. If I change my mind, I can always add the second option later.

**Comment by jrb-github** [comment]
So does this mean the browser_executable parameter is no longer supported?  Is there an intended retrofit for those of us who were using that (to use Edge instead of Chrome)?  Thanks!

**Comment by vgalin** [comment]
@jrb-github Not exactly. This only concerns the CLI script of `html2image`, and `browser_executable` has been removed because it was wrongly used as a parameter of the `screenshot` method, which no longer supports this parameter.

If you're only using `html2image` through Python files/scripts and not through the CLI, nothing changes for you. If you're using the CLI, it will "just" become functional again.

**Comment by jrb-github** [comment]
> @jrb-github Not exactly. This only concerns the CLI script of `html2image`, and `browser_executable` has been removed because it was wrongly used as a parameter of the `screenshot` method, which no longer supports this parameter.
> 
> If you're only using `html2image` through Python files/scripts and not through the CLI, nothing changes for you. If you're using the CLI, it will "just" become functional again.

Hm. Maybe I should branch this off into a separate issue, but I found this pull request because of a recent change in behavior where I was successfully using the `browser_executable` parameter in the Html2Image constructor (python code, not CLI), and when using the screenshot method on the resulting object, it no longer generates the correct image.  Obviously I'm not using this code as the change hasn't been committed yet, but it seemed like it must somehow be connected.

**Comment by satheler** [comment]
@vgalin Thanks for the review!!! I believe the best way is to leave it backwards compatible anyway.
I made the changes as you suggested on 9e96083

**Pull request merged**
